name       : qt5-imageformats
version    : 5.13.1
release    : 6
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtimageformats-everywhere-src-5.13.1.tar.xz : f6aa1e3fe6c3d786e211e4bd46a1349192efd82364739c0d708b7f2003a93ddf
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
