name       : qt5-imageformats
version    : 5.11.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qtimageformats-everywhere-src-5.11.2.tar.xz : 27e5d10551d0b5bf4799d09e5412ea2e6898b09aa1521ea24bce660ee6183a68
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
