name       : qt5-imageformats
version    : 5.12.1
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtimageformats-everywhere-src-5.12.1.tar.xz : 0425f35dbcc83cd5840e2d3a73ed4c57c426af9d6ac7b9fe3a40d23560653421
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
