name       : qt5-imageformats
version    : 5.15.1
release    : 9
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtimageformats-everywhere-src-5.15.1.tar.xz : 75e72b4c11df97af3ff64ed26df16864ce1220a1cc730e49074ab9d72f658568
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
