name       : qt5-imageformats
version    : 5.14.2
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.14/5.14.2/submodules/qtimageformats-everywhere-src-5.14.2.tar.xz : 733eca0165c15e046b106039c989dac7f6bc2ecf215396d965ed065369264f8c
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
