name       : qt5-imageformats
version    : 5.15.9
release    : 21
source     :
    - git|https://invent.kde.org/qt/qt/qtimageformats.git : c249f58541afa45955c23b75c1fb88c5e3e4d18b
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : desktop.qt
summary    : Additional image formats to use with Qt5
description: |
    The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(jasper)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
setup      : |
    %qmake CONFIG+=release qtimageformats.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
